require 'rassmalog' # loads the core of Rassmalog; this is necessary!

#
# Activate additional plugins, which provide useful Rake tasks.
#
require 'plugins/new' # allows easy creation of blog entry source files
require 'plugins/import' # allows you to import blog entries from feeds

#
# Define what work must be performed to generate
# your blog (when you run the "rake gen" command).
#
# To see a description of the Rake tasks in the
# list below, please run the "rake -T" command.
#
task :gen => [ :copy, :entry, :entry_list, :entry_meta, :search, :feed ]

#
# The primary news feed for your blog.
#
# See the API documentation for the feed() method in the user guide for help.
#
feed 'rss.xml', ENTRIES.first(3), BLOG.name, BLOG.info, false


